compatibility_date = "2024-12-20"
compatibility_flags = ["nodejs_compat_v2"]
main = "src/index.ts"
name = "triad-backend"

[limits]
cpu_ms = 4000

[triggers]
crons = [
  "*/1 * * * *", # Every minute
  "0 4,16 * * *", # Every day at 4am and 4pm
]

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "KV"
id = "3046170811b944e89778e8daa86e04db"
preview_id = "c57c56f7ee3049a5a9b5246f20a95b27"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_id = "313b925d-927c-41df-a77f-04e0cb8a4163"
database_name = "triad-db-prod"
migrations_dir = "drizzle"

[[durable_objects.bindings]]
class_name = "TrainData"
name = "TRAIN_DATA"

[[migrations]]
new_classes = ["TrainData"]
tag = "v1"
